create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

create table public.tags (
  id varchar(36) primary key default gen_random_uuid()::text,
  name varchar(50) not null,
  color varchar(20) not null default '#6366f1',
  created_at timestamptz not null default now()
);

create index tags_name_idx on public.tags (name);

create table public.tasks (
  id varchar(36) primary key default gen_random_uuid()::text,
  title varchar(200) not null,
  description text,
  date varchar(10),
  time_slot varchar(20),
  hours numeric(3, 1) not null default 1,
  tag_id varchar(36),
  priority varchar(20) not null default 'normal',
  status varchar(20) not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz default now(),
  constraint tasks_date_check check (
    date is null or date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
  ),
  constraint tasks_time_slot_check check (
    time_slot is null or time_slot in ('morning', 'afternoon', 'evening')
  ),
  constraint tasks_priority_check check (
    priority in ('urgent', 'normal')
  ),
  constraint tasks_status_check check (
    status in ('pending', 'completed')
  )
);

alter table public.tasks
  add constraint tasks_tag_id_fkey
  foreign key (tag_id) references public.tags (id) on delete set null;

create index tasks_date_idx on public.tasks (date);
create index tasks_time_slot_idx on public.tasks (time_slot);
create index tasks_status_idx on public.tasks (status);
create index tasks_priority_idx on public.tasks (priority);
create index tasks_tag_id_idx on public.tasks (tag_id);

create table public.health_check (
  id bigint generated by default as identity primary key,
  updated_at timestamptz not null default now()
);

create trigger tasks_set_updated_at
before update on public.tasks
for each row
execute function public.set_updated_at();

create trigger health_check_set_updated_at
before update on public.health_check
for each row
execute function public.set_updated_at();

alter table public.tags enable row level security;
alter table public.tasks enable row level security;
alter table public.health_check enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.tags to anon, authenticated;
grant select, insert, update, delete on table public.tasks to anon, authenticated;
grant select, insert, update, delete on table public.health_check to anon, authenticated;

create policy "tags_select_all"
on public.tags
for select
to anon, authenticated
using (true);

create policy "tags_insert_all"
on public.tags
for insert
to anon, authenticated
with check (true);

create policy "tags_update_all"
on public.tags
for update
to anon, authenticated
using (true)
with check (true);

create policy "tags_delete_all"
on public.tags
for delete
to anon, authenticated
using (true);

create policy "tasks_select_all"
on public.tasks
for select
to anon, authenticated
using (true);

create policy "tasks_insert_all"
on public.tasks
for insert
to anon, authenticated
with check (true);

create policy "tasks_update_all"
on public.tasks
for update
to anon, authenticated
using (true)
with check (true);

create policy "tasks_delete_all"
on public.tasks
for delete
to anon, authenticated
using (true);

create policy "health_check_select_all"
on public.health_check
for select
to anon, authenticated
using (true);

create policy "health_check_insert_all"
on public.health_check
for insert
to anon, authenticated
with check (true);

create policy "health_check_update_all"
on public.health_check
for update
to anon, authenticated
using (true)
with check (true);

create policy "health_check_delete_all"
on public.health_check
for delete
to anon, authenticated
using (true);
