create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name, avatar_url)
  values (
    new.id,
    coalesce(new.email, ''),
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    nullif(new.raw_user_meta_data ->> 'avatar_url', '')
  )
  on conflict (id) do update set
    email = excluded.email,
    display_name = excluded.display_name,
    avatar_url = excluded.avatar_url,
    updated_at = now();

  return new;
end;
$$;

revoke all on function public.handle_new_user() from public;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null unique,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tags (
  id varchar(36) primary key default gen_random_uuid()::text,
  user_id uuid not null references auth.users (id) on delete cascade,
  name varchar(50) not null,
  color varchar(20) not null default '#6366f1',
  created_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id varchar(36) primary key default gen_random_uuid()::text,
  user_id uuid not null references auth.users (id) on delete cascade,
  title varchar(200) not null,
  description text,
  date varchar(10),
  time_slot varchar(20),
  hours numeric(3, 1) not null default 1,
  tag_id varchar(36),
  priority varchar(20) not null default 'normal',
  status varchar(20) not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz default now(),
  constraint tasks_date_check check (
    date is null or date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
  ),
  constraint tasks_time_slot_check check (
    time_slot is null or time_slot in ('morning', 'afternoon', 'evening')
  ),
  constraint tasks_priority_check check (
    priority in ('urgent', 'normal')
  ),
  constraint tasks_status_check check (
    status in ('pending', 'completed')
  )
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'tasks_tag_id_fkey'
  ) then
    alter table public.tasks
      add constraint tasks_tag_id_fkey
      foreign key (tag_id) references public.tags (id) on delete set null;
  end if;
end
$$;

create table if not exists public.health_check (
  id bigint generated by default as identity primary key,
  updated_at timestamptz not null default now()
);

create index if not exists profiles_email_idx on public.profiles (email);
create index if not exists tags_user_id_idx on public.tags (user_id);
create index if not exists tags_name_idx on public.tags (name);
create index if not exists tasks_user_id_idx on public.tasks (user_id);
create index if not exists tasks_date_idx on public.tasks (date);
create index if not exists tasks_time_slot_idx on public.tasks (time_slot);
create index if not exists tasks_status_idx on public.tasks (status);
create index if not exists tasks_priority_idx on public.tasks (priority);
create index if not exists tasks_tag_id_idx on public.tasks (tag_id);

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at
before update on public.tasks
for each row
execute function public.set_updated_at();

drop trigger if exists health_check_set_updated_at on public.health_check;
create trigger health_check_set_updated_at
before update on public.health_check
for each row
execute function public.set_updated_at();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

drop trigger if exists on_auth_user_email_updated on auth.users;
create trigger on_auth_user_email_updated
after update of email on auth.users
for each row
execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.tags enable row level security;
alter table public.tasks enable row level security;
alter table public.health_check enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete on table public.profiles to authenticated;
grant select, insert, update, delete on table public.tags to authenticated;
grant select, insert, update, delete on table public.tasks to authenticated;
grant select on table public.health_check to authenticated;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "tags_select_own" on public.tags;
drop policy if exists "tags_insert_own" on public.tags;
drop policy if exists "tags_update_own" on public.tags;
drop policy if exists "tags_delete_own" on public.tags;
drop policy if exists "tasks_select_own" on public.tasks;
drop policy if exists "tasks_insert_own" on public.tasks;
drop policy if exists "tasks_update_own" on public.tasks;
drop policy if exists "tasks_delete_own" on public.tasks;
drop policy if exists "health_check_select_authenticated" on public.health_check;
drop policy if exists "health_check_insert_authenticated" on public.health_check;
drop policy if exists "health_check_update_authenticated" on public.health_check;
drop policy if exists "health_check_delete_authenticated" on public.health_check;

create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id);

create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check ((select auth.uid()) = id);

create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "tags_select_own"
on public.tags
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "tags_insert_own"
on public.tags
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "tags_update_own"
on public.tags
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "tags_delete_own"
on public.tags
for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "tasks_select_own"
on public.tasks
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "tasks_insert_own"
on public.tasks
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "tasks_update_own"
on public.tasks
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "tasks_delete_own"
on public.tasks
for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "health_check_select_authenticated"
on public.health_check
for select
to authenticated
using (true);
